pipeline{
    agent any
    environment{
      APP_NAME = 'cicd-ec2-deploy'
      DOCKERHUB_REPO = "${env.DOCKERHUB_REPO}"   // set in Jenkins job config
      IMAGE_TAG      = "build-${env.BUILD_NUMBER}"
      IMAGE_FULL     = "${DOCKERHUB_REPO}:${IMAGE_TAG}"
      EC2_HOST       = "${env.EC2_HOST}"         // set in Jenkins job config
      EC2_USER       = "${env.EC2_USER}"         // set in Jenkins job config (ubuntu)
    }

    stages{
        stage("checkout scm"){
            steps{
                checkout scm
            }
        }

        stage("Test"){
          steps {
                bat '''
                python -m venv .venv
                call .venv/Scripts/activate.bat
                pip install -r cicd-ec2-autodeploy/app/requirements.txt --quiet
                python -m pytest cicd-ec2-autodeploy/app -q
                '''
          }
        }
 
        stage("Build Docker image"){
            steps{
                bat '''
                docker build -t %IMAGE_FULL% -f cicd-ec2-autodeploy/docker/Dockerfile .
                '''

            }
        } 

        stage("docker push image"){
            steps{
                
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]){
                  sh '''
                    echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
                    docker push ${IMAGE_FULL}
                  '''                  
                  }
                
            }
        }

        stage("Deploy to EC2 (Blue/Green)") {
    steps {
        withCredentials([file(credentialsId: 'ec2-ssh-key-file', variable: 'SSH_KEY_FILE')]) {
            
            // Windows Jenkins runs bat with %VAR% for local ssh/scp commands
            bat """
                 icacls %SSH_KEY_FILE% /inheritance:r
                icacls %SSH_KEY_FILE% /grant:r "%USERNAME%:R"
                icacls %SSH_KEY_FILE% /remove "BUILTIN\\Users"
                icacls %SSH_KEY_FILE% /remove "Everyone"
                icacls %SSH_KEY_FILE% /grant:r "SYSTEM:F"
                icacls %SSH_KEY_FILE% /grant:r "BUILTIN\\Administrators:F"

                ssh -o StrictHostKeyChecking=no -i %SSH_KEY_FILE% ^
                    %EC2_USER%@%EC2_HOST% ^
                    "sudo mkdir -p /opt/%APP_NAME%/docker /opt/%APP_NAME%/scripts"

                scp -o StrictHostKeyChecking=no -i %SSH_KEY_FILE% ^
                    cicd-ec2-autodeploy/docker-compose.ec2.yml ^
                    %EC2_USER%@%EC2_HOST%:/tmp/docker-compose.ec2.yml

                scp -o StrictHostKeyChecking=no -i %SSH_KEY_FILE% ^
                    cicd-ec2-autodeploy/docker/nginx.conf ^
                    %EC2_USER%@%EC2_HOST%:/tmp/nginx.conf

                scp -o StrictHostKeyChecking=no -i %SSH_KEY_FILE% ^
                    cicd-ec2-autodeploy/scripts/deploy_bluegreen.sh ^
                    %EC2_USER%@%EC2_HOST%:/tmp/deploy_bluegreen.sh

                ssh -o StrictHostKeyChecking=no -i %SSH_KEY_FILE% ^
                    %EC2_USER%@%EC2_HOST% ^
                    "set -e && sudo apt-get install -y dos2unix -qq && sudo mv /tmp/docker-compose.ec2.yml /opt/%APP_NAME%/docker-compose.ec2.yml && sudo mv /tmp/nginx.conf /opt/%APP_NAME%/docker/nginx.conf && sudo mv /tmp/deploy_bluegreen.sh /opt/%APP_NAME%/scripts/deploy_bluegreen.sh && sudo dos2unix /opt/%APP_NAME%/scripts/deploy_bluegreen.sh && sudo chmod +x /opt/%APP_NAME%/scripts/deploy_bluegreen.sh && sudo IMAGE_FULL=%IMAGE_FULL% APP_VERSION=%IMAGE_TAG% /opt/%APP_NAME%/scripts/deploy_bluegreen.sh"
                 }
          }
        }
    }
}               

post{
    always{
        sh "docker logout || true"
        sh "rm -rf .env || true"
    }
  }


